In [ ]:
with open("hostel_bois.txt", "r", encoding="utf-8") as f:
    lines = f.readlines()

print("Total lines:", len(lines))

Total lines: 3178


In [ ]:
for i in range(5):
  print(lines[i])

01/04/24, 01:12 - Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them. Tap to learn more.

01/04/24, 01:13 - Priya created group "Hostel Bois 4ever"

01/04/24, 01:14 - Priya added you

01/04/24, 01:17 - Rahul: scene fix

01/04/24, 01:17 - Rahul: haan



In [ ]:
messages=[]

In [ ]:
for line in lines:
    line = line.strip()

    if line == "":
        continue

    if " - " not in line:
        continue

    parts = line.split(" - ", 1)

    timestamp = parts[0]
    data = parts[1]

    if ": " not in data:
        continue

    sender, text = data.split(": ", 1)

    message = {
        "timestamp": timestamp,
        "sender": sender,
        "text": text
    }

    messages.append(message)

In [ ]:
print("Total parsed messages:", len(messages))
print(messages[:5])

Total parsed messages: 9522
[{'timestamp': '01/04/24, 01:17', 'sender': 'Rahul', 'text': 'scene fix'}, {'timestamp': '01/04/24, 01:17', 'sender': 'Rahul', 'text': 'haan'}, {'timestamp': '01/04/24, 01:18', 'sender': 'Rahul', 'text': 'kya scene'}, {'timestamp': '01/04/24, 02:13', 'sender': 'Rahul', 'text': 'abhi free hai?'}, {'timestamp': '01/04/24, 02:13', 'sender': 'Rahul', 'text': 'abey'}]


In [ ]:
person_count = {}

for msg in messages:
    name = msg["sender"]

    if name in person_count:
        person_count[name] += 1
    else:
        person_count[name] = 1

print(person_count)

{'Rahul': 2859, 'Priya': 2154, 'Karan': 1062, 'Neha': 1905, 'Aman': 1470, 'Vikas': 72}


In [ ]:
sorted_people = sorted(
    person_count.items(),
    key=lambda x: x[1],
    reverse=True
)

for name, count in sorted_people:
    print(name, count)

Rahul 2859
Priya 2154
Neha 1905
Aman 1470
Karan 1062
Vikas 72


In [ ]:
word_count = {}

stop_words = [
    "i", "is", "the", "a", "and", "or", "to",
    "of", "in", "on", "for", "it", "this"
]

for msg in messages:
    text = msg["text"].lower()

    words = text.split()

    for word in words:
        word = word.strip(".,!?()[]{}\"'")

        if word not in stop_words and word != "":
            if word in word_count:
                word_count[word] += 1
            else:
                word_count[word] = 1

In [ ]:
top_words = sorted(
    word_count.items(),
    key=lambda x: x[1],
    reverse=True
)

print("TOP 10 WORDS")
print("-" * 30)

for word, count in top_words[:10]:
    print(f"{word:<10} : {count}")

TOP 10 WORDS
------------------------------
was        : 1200
how        : 963
guys       : 954
you        : 936
so         : 876
about      : 822
hai        : 804
am         : 780
today      : 771
at         : 771


In [ ]:
import numpy as np

In [ ]:
participants = []

for msg in messages:
    name = msg["sender"]

    if name not in participants:
        participants.append(name)

print(participants)

['Rahul', 'Priya', 'Karan', 'Neha', 'Aman', 'Vikas']


In [ ]:
heatmap = np.zeros((len(participants), 24), dtype=int)

print(heatmap)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [ ]:
for msg in messages:
    name = msg["sender"]

    time = msg["timestamp"].split(", ")[1]
    hour = int(time.split(":")[0])

    row = participants.index(name)

    heatmap[row][hour] += 1

In [ ]:
print(heatmap)

[[  9  45  51  51  66  30  51  51  72  51  75  45 174 144 135 159 219 147
  315 228 123 276 180 162]
 [  0   0   0   0   0   0  39  60 141 195 186 183 171 144 132  87  96 120
  114 180 129  96  54  27]
 [  0   0   0   0   0   0   0  12  36  48  60  48 111  75  96  81  81  81
   75  96  69  42  27  24]
 [  0   0   0   0   0  57   9  39 108 156 156  66 117 108  81  30 111 141
  186 150 135  81  84  90]
 [162 201 198 180 264   0   0   0   0   0   0   0   0   0  42  33  57  21
   48  24  39  33   0 168]
 [  0   0   0   0   0   0   0   3   9   3   3   0   6   6   0   3   3   9
    6   6   3   3   3   6]]


In [ ]:
print("ACTIVITY HEATMAP")
print("      ", end="")

for hour in range(24):
    print(f"{hour:02}", end=" ")

print()

for i, person in enumerate(participants):
    print(f"{person:<6}", end=" ")

    for value in heatmap[i]:
        print(f"{value:02}", end=" ")

    print()

ACTIVITY HEATMAP
      00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 
Rahul  09 45 51 51 66 30 51 51 72 51 75 45 174 144 135 159 219 147 315 228 123 276 180 162 
Priya  00 00 00 00 00 00 39 60 141 195 186 183 171 144 132 87 96 120 114 180 129 96 54 27 
Karan  00 00 00 00 00 00 00 12 36 48 60 48 111 75 96 81 81 81 75 96 69 42 27 24 
Neha   00 00 00 00 00 57 09 39 108 156 156 66 117 108 81 30 111 141 186 150 135 81 84 90 
Aman   162 201 198 180 264 00 00 00 00 00 00 00 00 00 42 33 57 21 48 24 39 33 00 168 
Vikas  00 00 00 00 00 00 00 03 09 03 03 00 06 06 00 03 03 09 06 06 03 03 03 06 


In [ ]:
from datetime import datetime, timedelta

In [ ]:
for msg in messages:
    msg["datetime"] = datetime.strptime(
        msg["timestamp"],
        "%d/%m/%y, %H:%M"
    )

In [ ]:
response_times = {}

for i in range(1, len(messages)):
    current = messages[i]
    previous = messages[i - 1]

    if current["sender"] != previous["sender"]:

        gap = (
            current["datetime"] -
            previous["datetime"]
        ).total_seconds() / 60

        name = current["sender"]

        if name not in response_times:
            response_times[name] = []

        response_times[name].append(gap)

In [ ]:
average_response = {}

for person, times in response_times.items():
    average_response[person] = sum(times) / len(times)

for person, avg in average_response.items():
    print(person, ":", round(avg, 2), "minutes")

Priya : 41.99 minutes
Rahul : -238.25 minutes
Karan : 36.62 minutes
Neha : 39.45 minutes
Aman : 55.36 minutes
Vikas : 46.3 minutes


In [ ]:
fastest = min(
    average_response,
    key=average_response.get
)

slowest = max(
    average_response,
    key=average_response.get
)

print("Fastest replier:", fastest)
print(
    "Average time:",
    round(average_response[fastest], 2),
    "minutes"
)

print("Slowest replier:", slowest)
print(
    "Average time:",
    round(average_response[slowest], 2),
    "minutes"
)

Fastest replier: Rahul
Average time: -238.25 minutes
Slowest replier: Aman
Average time: 55.36 minutes


In [ ]:
person_days = {}

for msg in messages:
    name = msg["sender"]
    day = msg["datetime"].date()

    if name not in person_days:
        person_days[name] = set()

    person_days[name].add(day)

print(person_days)

{'Rahul': {datetime.date(2024, 5, 13), datetime.date(2024, 4, 26), datetime.date(2024, 4, 27), datetime.date(2024, 5, 10), datetime.date(2024, 5, 28), datetime.date(2024, 4, 8), datetime.date(2024, 4, 15), datetime.date(2024, 4, 5), datetime.date(2024, 5, 18), datetime.date(2024, 5, 3), datetime.date(2024, 4, 28), datetime.date(2024, 4, 29), datetime.date(2024, 4, 4), datetime.date(2024, 4, 10), datetime.date(2024, 4, 23), datetime.date(2024, 5, 19), datetime.date(2024, 5, 22), datetime.date(2024, 5, 23), datetime.date(2024, 5, 30), datetime.date(2024, 4, 24), datetime.date(2024, 5, 9), datetime.date(2024, 4, 30), datetime.date(2024, 4, 2), datetime.date(2024, 4, 1), datetime.date(2024, 5, 12), datetime.date(2024, 4, 20), datetime.date(2024, 5, 16), datetime.date(2024, 5, 6), datetime.date(2024, 5, 8), datetime.date(2024, 4, 25), datetime.date(2024, 5, 1), datetime.date(2024, 5, 2), datetime.date(2024, 5, 11), datetime.date(2024, 4, 14), datetime.date(2024, 5, 4), datetime.date(2024, 5

In [ ]:
all_days = set()

for msg in messages:
    all_days.add(msg["datetime"].date())

total_days = len(all_days)

for person in person_days:
    silent_days = total_days - len(person_days[person])

    print(person, "was silent for", silent_days, "days")

Rahul was silent for 0 days
Priya was silent for 0 days
Karan was silent for 0 days
Neha was silent for 0 days
Aman was silent for 0 days
Vikas was silent for 44 days


In [ ]:
personality = {}

In [ ]:
burst_count = {}
current_sender = ""
count = 0

for msg in messages:
    sender = msg["sender"]

    if sender == current_sender:
        count += 1
    else:
        if current_sender != "":
            burst_count[current_sender] = max(
                burst_count.get(current_sender, 0),
                count
            )

        current_sender = sender
        count = 1

print("Spammer scores:", burst_count)

Spammer scores: {'Rahul': 13, 'Priya': 7, 'Karan': 4, 'Neha': 9, 'Aman': 10, 'Vikas': 2}


In [ ]:
night_count = {}
total_count = {}

for msg in messages:
    name = msg["sender"]
    hour = msg["datetime"].hour

    total_count[name] = total_count.get(name, 0) + 1

    if hour >= 23 or hour <= 4:
        night_count[name] = night_count.get(name, 0) + 1

for person in total_count:
    percentage = (night_count.get(person, 0) /
                  total_count[person]) * 100

    print(person, "Night %:", round(percentage, 2))

Rahul Night %: 13.43
Priya Night %: 1.25
Karan Night %: 2.26
Neha Night %: 4.72
Aman Night %: 79.8
Vikas Night %: 8.33


In [ ]:
caring_words = [
    "okay", "safe", "eat",
    "sleep", "please",
    "take care"
]

care_score = {}

for msg in messages:
    text = msg["text"].lower()

    for word in caring_words:
        if word in text:
            name = msg["sender"]

            care_score[name] = (
                care_score.get(name, 0) + 1
            )

print(care_score)

{'Priya': 1389, 'Karan': 87, 'Aman': 297, 'Neha': 69}


In [ ]:
length_data = {}

for msg in messages:
    name = msg["sender"]

    words = len(msg["text"].split())

    if name not in length_data:
        length_data[name] = []

    length_data[name].append(words)

for person, data in length_data.items():
    average = sum(data) / len(data)

    print(person,
          "Average words:",
          round(average, 2))

Rahul Average words: 2.56
Priya Average words: 4.98
Karan Average words: 55.66
Neha Average words: 5.27
Aman Average words: 4.99
Vikas Average words: 1.83


In [ ]:
drama_score = {}

for msg in messages:
    text = msg["text"]

    if text.isupper() or text.count("!") >= 2:
        name = msg["sender"]

        drama_score[name] = (
            drama_score.get(name, 0) + 1
        )

print(drama_score)

{'Neha': 1185}


In [ ]:
ghost_score = {}

for person in person_days:
    ghost_score[person] = (
        total_days - len(person_days[person])
    )

print(ghost_score)

{'Rahul': 0, 'Priya': 0, 'Karan': 0, 'Neha': 0, 'Aman': 0, 'Vikas': 44}


In [ ]:
print("PERSONALITY ARCHETYPES")
print("----------------------")

print("Rahul  → THE SPAMMER")
print("Priya  → THE GROUP MOM")
print("Aman   → THE NIGHT OWL")
print("Karan  → THE STORYTELLER")
print("Neha   → THE DRAMA QUEEN")
print("Vikas  → THE GHOST")

PERSONALITY ARCHETYPES
----------------------
Rahul  → THE SPAMMER
Priya  → THE GROUP MOM
Aman   → THE NIGHT OWL
Karan  → THE STORYTELLER
Neha   → THE DRAMA QUEEN
Vikas  → THE GHOST


In [ ]:
print("=" * 60)
print("              GROUPDNA REPORT")
print("=" * 60)
print()

              GROUPDNA REPORT



In [ ]:
print("GROUP OVERVIEW")
print("-" * 30)

print("Total Messages:", len(messages))
print("Total Participants:", len(participants))

print("\nMessages Per Person")

for name, count in sorted_people:
    print(f"{name:<10} : {count}")

print()

GROUP OVERVIEW
------------------------------
Total Messages: 9522
Total Participants: 6

Messages Per Person
Rahul      : 2859
Priya      : 2154
Neha       : 1905
Aman       : 1470
Karan      : 1062
Vikas      : 72



In [ ]:
print("TOP WORDS")
print("-" * 30)

for word, count in top_words[:10]:
    bar = "█" * (count // 20)

    print(f"{word:<10} {bar} {count}")

print()

TOP WORDS
------------------------------
was        ████████████████████████████████████████████████████████████ 1200
how        ████████████████████████████████████████████████ 963
guys       ███████████████████████████████████████████████ 954
you        ██████████████████████████████████████████████ 936
so         ███████████████████████████████████████████ 876
about      █████████████████████████████████████████ 822
hai        ████████████████████████████████████████ 804
am         ███████████████████████████████████████ 780
today      ██████████████████████████████████████ 771
at         ██████████████████████████████████████ 771



In [ ]:
print("ACTIVITY HEATMAP")
print("-" * 30)

print("      ", end="")

for hour in range(24):
    print(f"{hour:02}", end=" ")

print()

for i, person in enumerate(participants):
    print(f"{person:<6}", end=" ")

    for value in heatmap[i]:
        if value == 0:
            symbol = "."
        elif value < 10:
            symbol = "░"
        elif value < 30:
            symbol = "▒"
        else:
            symbol = "█"

        print(symbol, end="  ")

    print()

print()

ACTIVITY HEATMAP
------------------------------
      00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 
Rahul  ░  █  █  █  █  █  █  █  █  █  █  █  █  █  █  █  █  █  █  █  █  █  █  █  
Priya  .  .  .  .  .  .  █  █  █  █  █  █  █  █  █  █  █  █  █  █  █  █  █  ▒  
Karan  .  .  .  .  .  .  .  ▒  █  █  █  █  █  █  █  █  █  █  █  █  █  █  ▒  ▒  
Neha   .  .  .  .  .  █  ░  █  █  █  █  █  █  █  █  █  █  █  █  █  █  █  █  █  
Aman   █  █  █  █  █  .  .  .  .  .  .  .  .  .  █  █  █  ▒  █  ▒  █  █  .  █  
Vikas  .  .  .  .  .  .  .  ░  ░  ░  ░  .  ░  ░  .  ░  ░  ░  ░  ░  ░  ░  ░  ░  



In [ ]:
print("RESPONSE PATTERNS")
print("-" * 30)

for person, avg in average_response.items():
    print(
        f"{person:<10}: {round(avg,2)} minutes"
    )

print()

RESPONSE PATTERNS
------------------------------
Priya     : 41.99 minutes
Rahul     : -238.25 minutes
Karan     : 36.62 minutes
Neha      : 39.45 minutes
Aman      : 55.36 minutes
Vikas     : 46.3 minutes



In [ ]:
print("SILENT DAYS")
print("-" * 30)

for person in person_days:
    silent = total_days - len(person_days[person])

    print(f"{person:<10}: {silent} days")

print()

SILENT DAYS
------------------------------
Rahul     : 0 days
Priya     : 0 days
Karan     : 0 days
Neha      : 0 days
Aman      : 0 days
Vikas     : 44 days



In [ ]:
print("PERSONALITY ARCHETYPES")
print("-" * 30)

print("Rahul  → THE SPAMMER")
print("Priya  → THE GROUP MOM")
print("Aman   → THE NIGHT OWL")
print("Karan  → THE STORYTELLER")
print("Neha   → THE DRAMA QUEEN")
print("Vikas  → THE GHOST")

PERSONALITY ARCHETYPES
------------------------------
Rahul  → THE SPAMMER
Priya  → THE GROUP MOM
Aman   → THE NIGHT OWL
Karan  → THE STORYTELLER
Neha   → THE DRAMA QUEEN
Vikas  → THE GHOST


In [ ]:
print()
print("=" * 60)
print("      Generated by GroupDNA using Python + NumPy")
print("=" * 60)


      Generated by GroupDNA using Python + NumPy
